import type { WorkflowProjection } from './types'

export const SEEDED_WORKFLOW: WorkflowProjection = {
  workflowId: 'wf-checkpoint-recovery',
  title: 'Harden cross-harness checkpoint recovery',
  objective:
    'Make interrupted workflows recoverable across Codex, Grok, and Claude without trusting a single process or chat session.',
  currentPhase: 'plan',
  cycleCount: 2,
  updatedAt: '2026-07-26T12:14:00.000Z',
  phases: [
    {
      id: 'plan',
      label: 'Plan',
      status: 'active',
      owner: 'Platform architecture',
      harness: 'Codex',
      summary: 'Remediate stale claims and reject incompatible state before execution resumes.',
    },
    {
      id: 'execute',
      label: 'Execute',
      status: 'queued',
      owner: 'Runtime implementation',
      harness: 'Grok',
      summary: 'Apply the approved claim lease and schema guard changes.',
    },
    {
      id: 'review',
      label: 'Review',
      status: 'blocked',
      owner: 'Independent review',
      harness: 'Claude',
      summary: 'Cycle one found two deployment-blocking recovery defects.',
    },
    {
      id: 'ready',
      label: 'Deploy gate',
      status: 'queued',
      owner: 'Project maintainer',
      harness: 'Human',
      summary: 'Available only after blocking findings are cleared and validation is complete.',
    },
  ],
  narratives: {
    plan: {
      now: 'Cycle 02 is defining the smallest durable remediation for two blocking recovery findings.',
      why: 'The previous process lock can survive neither an interrupted harness nor a Git handoff.',
      next: 'Approve the lease strategy, then hand the constrained execution packet to Grok.',
    },
    execute: {
      now: 'Execution is queued until the remediation decision is recorded.',
      why: 'Changing the claim algorithm before agreeing on expiry semantics could create split ownership.',
      next: 'Implement the selected lease protocol and checkpoint schema guard as one bounded batch.',
    },
    review: {
      now: 'Cycle 01 review is preserved as evidence; its blockers opened remediation cycle 02.',
      why: 'A review remains useful only when findings retain evidence, root cause, and cycle impact.',
      next: 'Re-run recovery, concurrency, corruption, and compatibility checks after execution.',
    },
    ready: {
      now: 'Deployment readiness is withheld while two blocking findings remain unresolved.',
      why: 'Readiness is derived from review and validation; deployment authorization is a separate human event.',
      next: 'Complete another Plan, Execute, Review loop. No deployment action is available here.',
    },
  },
  cycles: [
    {
      number: 2,
      label: 'Recovery remediation',
      status: 'active',
      summary: 'Replace process-bound ownership and reject incompatible checkpoints before resume.',
    },
    {
      number: 1,
      label: 'Initial vertical slice',
      status: 'complete',
      summary: 'Core handoff path worked; review exposed stale ownership and schema drift risks.',
    },
  ],
  decisions: [
    {
      id: 'decision-lease-model',
      title: 'How should a harness claim expire?',
      context:
        'A crashed process cannot release its claim, while wall-clock-only expiry can steal work from a slow but healthy harness.',
      options: [
        {
          id: 'heartbeat-lease',
          label: 'Heartbeat lease',
          summary: 'Renew a short lease while active; require an explicit takeover after expiry.',
        },
        {
          id: 'manual-release',
          label: 'Manual release only',
          summary: 'Simple history, but every interrupted session requires recovery by a maintainer.',
        },
        {
          id: 'timestamp-only',
          label: 'Timestamp expiry',
          summary: 'Portable and cheap, but vulnerable to clock skew and long-running commands.',
        },
      ],
      selectedOptionId: null,
      requiresApproval: true,
    },
    {
      id: 'decision-schema-policy',
      title: 'Checkpoint compatibility policy',
      context: 'Resume must fail safely when a future schema cannot be interpreted by the current tool.',
      options: [
        {
          id: 'strict-major',
          label: 'Strict major version',
          summary: 'Reject newer major versions and preserve the original artifact for migration.',
        },
        {
          id: 'best-effort',
          label: 'Best-effort parse',
          summary: 'Continues more often but can silently discard workflow-critical fields.',
        },
      ],
      selectedOptionId: 'strict-major',
      requiresApproval: false,
    },
  ],
  annotations: [
    {
      id: 'annotation-1',
      author: 'M. Abdelhady',
      harness: 'Maintainer',
      body: 'Treat Git as the exchange boundary. A local database may project state, but it must never become the only durable copy.',
      createdAt: '2026-07-26T11:48:00.000Z',
    },
  ],
  findings: [
    {
      id: 'finding-stale-claim',
      title: 'Interrupted owner leaves the workflow permanently claimed',
      severity: 'blocking',
      classification: 'blocking',
      evidence: 'Recovery fixture retains owner=execute-grok after the process is terminated before checkpoint.',
      component: 'Claim coordinator',
      rootCause: 'Ownership is represented by process lifetime rather than a renewable, persisted lease.',
      resolution: 'Persist lease expiry and heartbeat events; require an explicit, audited takeover event.',
      requiresCycle: true,
    },
    {
      id: 'finding-schema-guard',
      title: 'Newer checkpoints are accepted with missing fields',
      severity: 'blocking',
      classification: 'blocking',
      evidence: 'A schema v2 fixture is reduced as v1 and loses deployment authorization history.',
      component: 'Workflow loader',
      rootCause: 'The parser validates shape fragments but does not enforce schema-major compatibility.',
      resolution: 'Reject unknown major versions before replay and emit a migration-required diagnostic.',
      requiresCycle: true,
    },
    {
      id: 'finding-log-density',
      title: 'Command transcript is difficult to scan',
      severity: 'medium',
      classification: 'non-blocking',
      evidence: 'Successful and failed command events share identical visual treatment in the report projection.',
      component: 'Execution report',
      rootCause: 'The projection lacks semantic grouping for command outcomes.',
      resolution: 'Group transcript entries by outcome while retaining chronological source order.',
      requiresCycle: false,
    },
    {
      id: 'finding-copy-action',
      title: 'Add a copy command affordance to recovery diagnostics',
      severity: 'low',
      classification: 'improvement',
      evidence: 'Recovery instructions are currently selectable but require manual command extraction.',
      component: 'Diagnostic report',
      rootCause: 'The first slice prioritized durable evidence over convenience actions.',
      resolution: 'Add a labeled copy action with a non-color success announcement.',
      requiresCycle: false,
    },
  ],
  validations: [
    {
      id: 'validation-replay',
      label: 'Deterministic event replay',
      status: 'passed',
      detail: 'Equivalent event DAGs produce the same projection.',
    },
    {
      id: 'validation-handoff',
      label: 'Cross-harness handoff',
      status: 'passed',
      detail: 'Codex plan state was claimed and resumed by Grok.',
    },
    {
      id: 'validation-stale-claim',
      label: 'Interrupted claim recovery',
      status: 'failed',
      detail: 'A terminated owner remains active without a manual state edit.',
    },
    {
      id: 'validation-schema',
      label: 'Forward schema guard',
      status: 'failed',
      detail: 'Unknown major versions are not rejected before replay.',
    },
    {
      id: 'validation-security',
      label: 'Loopback boundary review',
      status: 'pending',
      detail: 'Re-run after the remediation implementation changes the claim endpoint.',
    },
  ],
  artifacts: [
    {
      id: 'artifact-plan',
      label: 'Remediation plan',
      path: '.phasewire/workflows/wf-checkpoint-recovery/cycles/02/plan.md',
      kind: 'Plan',
      phase: 'plan',
    },
    {
      id: 'artifact-events',
      label: 'Portable event history',
      path: '.phasewire/workflows/wf-checkpoint-recovery/events/',
      kind: 'Event log',
      phase: 'execute',
    },
    {
      id: 'artifact-review',
      label: 'Cycle 01 review',
      path: '.phasewire/workflows/wf-checkpoint-recovery/cycles/01/review.md',
      kind: 'Review',
      phase: 'review',
    },
  ],
  events: [
    {
      id: 'event-remediation',
      label: 'Remediation cycle opened',
      description: 'Two blocking findings returned the workflow to Plan.',
      at: '2026-07-26T12:14:00.000Z',
      phase: 'plan',
      harness: 'Codex',
    },
    {
      id: 'event-review',
      label: 'Review completed with blockers',
      description: 'Recovery and compatibility findings prevented readiness.',
      at: '2026-07-26T12:08:00.000Z',
      phase: 'review',
      harness: 'Claude',
    },
    {
      id: 'event-execute',
      label: 'Initial execution checkpointed',
      description: 'Implementation and validation evidence were persisted for review.',
      at: '2026-07-26T11:54:00.000Z',
      phase: 'execute',
      harness: 'Grok',
    },
  ],
  executionChanges: [
    {
      path: 'packages/core/src/store.ts',
      summary: 'Added immutable event append and deterministic projection rebuild.',
      status: 'added',
    },
    {
      path: 'packages/core/src/claims.ts',
      summary: 'Recorded cross-harness ownership and explicit handoff events.',
      status: 'changed',
    },
    {
      path: 'packages/core/src/schema.ts',
      summary: 'Validated the required checkpoint fields before replay.',
      status: 'changed',
    },
  ],
  issueResolution: {
    problem: 'The initial prototype lost continuity when work moved between harnesses.',
    rootCause: 'State lived partly in process memory and partly in provider-specific conversation history.',
    candidates: ['Provider adapters', 'Shared SQLite authority', 'Git-portable immutable events'],
    selected: 'Git-portable immutable events with a disposable local projection',
    why: 'It survives session changes, remains inspectable in the project, and can be rebuilt without a daemon.',
    implementation: 'Append validated events, derive state with a pure reducer, and checkpoint phase evidence by cycle.',
    validation: 'Replay and cross-harness handoff pass; stale-claim and forward-schema cases require remediation.',
  },
  planApproved: false,
  planApprovalAction: 'approve-plan',
  deploymentReady: false,
  deploymentAuthorized: false,
}
