export const selectors = {
  actionError: '[data-testid="action-error"]',
  annotationInput: '[data-testid="annotation-input"]',
  annotationSubmit: '[data-testid="submit-annotation"]',
  appShell: '[data-testid="app-shell"]',
  approvePlan: '[data-testid="approve-plan"]',
  authorizeDeployment: '[data-testid="authorize-deployment"]',
  decisionCards: '[data-testid^="decision-card-"]',
  decisionOutcome: '[data-testid="decision-outcome-input"]',
  decisionTitle: '[data-testid="decision-title-input"]',
  directionToggle: '[data-testid="direction-toggle"]',
  mainReport: '#main-report',
  liveAnnouncement: '[data-testid="live-announcement"]',
  offlineBanner: '[data-testid="offline-banner"]',
  phaseExecute: '[data-testid="phase-execute"]',
  phasePlan: '[data-testid="phase-plan"]',
  phaseReady: '[data-testid="phase-ready"]',
  phaseReview: '[data-testid="phase-review"]',
  recordDecision: '[data-testid="record-new-decision"]',
  reportCanvas: '[data-testid="report-canvas"]',
  reportTitle: '[data-testid="report-title"]',
  staleBanner: '[data-testid="stale-banner"]',
  workflowTitleDisclosure: '[data-testid="workflow-title-disclosure"]',
  workflowTitleToggle: '[data-testid="workflow-title-toggle"]',
} as const
